# Generated by Django 5.0 on 2024-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, upload_to='medicine_images/'),
        ),
    ]
